/* Original visual directions. Shared by the page generator and the selector. */
globalThis.SKYMONI_WORLDS = [
 {key:'sky',name:'立体字形',family:'雕塑',file:'concept-03-sculpture.html',layout:'editorial',bg:'#edf5fc',ink:'#24465a',accent:'#498dbb',symbol:'sky',title:'让好奇，拥有形状。',description:'通透字形占满首屏，缩成贯穿页面的品牌印记。作品、手账与人物沿同一条蓝色线索展开。',action:'切换字形材质',chapters:['从一个字开始','让想法成形','留下创作的笔迹','遇见一起创造的人','让下一次创造发生']},
 {key:'cloud',name:'陶瓷云雕塑',family:'雕塑',file:'concept-03-cloud-object.html',layout:'gallery',bg:'#f2f0e9',ink:'#41483e',accent:'#9b865b',symbol:'☁',title:'把好奇，捏成一朵云。',description:'陶瓷云、暖白展厅和细金线贯穿全页；每一章节像走入下一间展厅。',action:'让云舒展',chapters:['柔软的开始','陈列一些小小的可能','把灵感写进展签','作品背后的温度','把想法交给云']},
 {key:'knot',name:'镜面回环',family:'雕塑',file:'concept-03-chrome-knot.html',layout:'poster',bg:'#0d1019',ink:'#dce5f3',accent:'#b4a6ef',symbol:'∞',title:'打破，既定形状。',description:'镜面结体转动、松开；银色轨迹延续到作品索引、档案页和人物卡。',action:'松开这个结',chapters:['一条没有终点的线','让想法彼此交错','追溯每一次转折','与不同的人相连','连接下一种可能']},
 {key:'archive',name:'悬浮作品群',family:'空间',file:'concept-03-floating-archive.html',layout:'contact',bg:'#f3f6f1',ink:'#24484c',accent:'#4a8a82',symbol:'▱',title:'想法，不必整齐排列。',description:'漂浮海报收成一册，接着进入作品陈列、创作手账与作者名片，形成完整的编辑叙事。',action:'作品收拢成册',chapters:['尚未装订的作品集','把每一页展开','翻进背后的故事','认识这一册的作者','故事还在继续']},
 {key:'tunnel',name:'光之隧道',family:'沉浸',file:'concept-03-light-tunnel.html',layout:'cinema',bg:'#040914',ink:'#c2e6f5',accent:'#77dbe7',symbol:'□',title:'好奇，自有引力。',description:'滚动穿过光门，光门缩为章节边界。作品、手账、人物依次成为隧道里的站点。',action:'暂停光环波动',chapters:['穿过第一束光','抵达作品之境','进入创作内部','看见同行者','下一扇门已经打开']},
 {key:'orbit',name:'卫星花园',family:'空间',layout:'orbital',bg:'#101827',ink:'#edf0ea',accent:'#d4f09e',symbol:'◉',title:'每个想法，<br>都有自己的引力。',description:'巨型行星与卫星绕行。滚动时轨道转成章节导航，小作品、创作记录和伙伴成为同一星系。',action:'展开卫星轨道',chapters:['引力的起点','沿轨道遇见作品','记录一次次发射','我们的同行星','接入更大的宇宙']},
 {key:'ribbon',name:'绸带叙事',family:'雕塑',layout:'ribbon',bg:'#f3eae3',ink:'#663731',accent:'#c66951',symbol:'∿',title:'让故事，<br>顺着灵感流动。',description:'一条有折面反光的红色绸带缓慢舒展，从首屏流入作品，再绕过手账和人物，最后汇成落款。',action:'舒展绸带',chapters:['从一条线出发','流经一些作品','折进创作的内页','把彼此编进故事','留一个新的开头']},
 {key:'prism',name:'棱镜实验室',family:'光学',layout:'split',bg:'#f0eff6',ink:'#302e54',accent:'#8079dd',symbol:'◇',title:'换一个角度，<br>看见更多可能。',description:'旋转多面棱镜、色散光束和非对称双栏。棱镜在章节间转面，作品、记录和人物是不同切面。',action:'打开棱镜切面',chapters:['一束光的可能','作品的不同切面','折射背后的想法','照见彼此的光','让能力折射出去']},
 {key:'bloom',name:'机械花园',family:'雕塑',layout:'botanical',bg:'#e9ede4',ink:'#344c36',accent:'#d0805d',symbol:'✳',title:'给好奇，<br>一点生长的空间。',description:'三维花瓣逐层开合。滚动进入标本式作品陈列，再到生长日记与园丁名片；整页如一座花园。',action:'让花朵绽放',chapters:['埋下一颗好奇','看看长出的作品','记录每一次生长','认识照料花园的人','把种子交给下一阵风']},
 {key:'signal',name:'粒子思维场',family:'沉浸',layout:'terminal',bg:'#060d13',ink:'#ddf5eb',accent:'#68dfb2',symbol:'⁙',title:'思绪，<br>正在连线。',description:'数千粒子在球体与平面之间聚合；扫描式标题、带序号的作品索引和网格人物卡延续同一个信息场。',action:'切换粒子聚合',chapters:['捕捉一个信号','发现可见的成果','读取创作记录','识别同行的节点','把能力连接上线']},
 {key:'paper',name:'折纸来信',family:'叙事',layout:'letter',bg:'#f6f0df',ink:'#514b3d',accent:'#ae6048',symbol:'⌁',title:'把一个念头，<br>折成远方。',description:'有真实折面的纸翼缓慢扇动，邮戳、页码与错落纸页串起作品和手账，结尾是一封继续写下去的信。',action:'展开纸翼',chapters:['写给好奇的你','随信附上一些作品','翻到信纸的背面','这些名字也在信里','期待下一次来信']},
 {key:'mobile',name:'平衡的游乐场',family:'空间',layout:'asymmetric',bg:'#ece9e3',ink:'#323b46',accent:'#bd533e',symbol:'┬',title:'认真创作，<br>轻轻玩耍。',description:'悬挂平衡雕塑由杆、球与彩色圆片组成，随鼠标轻摆。作品和人物沿交错的悬挂层级展开。',action:'改变平衡姿态',chapters:['保持一点好玩的失衡','挂起最近的作品','看看它们如何平衡','一起玩耍的人','留一个位置给新想法']},
 {key:'voxel',name:'云端微缩城',family:'空间',layout:'city',bg:'#e5ecf2',ink:'#34536e',accent:'#ec9870',symbol:'▦',title:'把小小的想法，<br>建成一座城。',description:'等距视角的三维微缩城市。滚动像沿街前进：作品是街区、手账是档案馆、伙伴是邻居，终点是连接站。',action:'展开城市街区',chapters:['欢迎来到微缩城','走进作品街区','在档案馆停一会儿','认识街角的邻居','从连接站再次出发']},
 {key:'wave',name:'潮汐工作室',family:'沉浸',layout:'horizon',bg:'#102b36',ink:'#d9eeec',accent:'#84c5be',symbol:'≈',title:'让想法，<br>像潮水一样抵达。',description:'整片三维波面构成地平线。章节沿潮线出现，作品露出水面，手账像航海记录，结尾回到开放海域。',action:'改变潮汐方向',chapters:['听见第一阵潮声','潮水带来的作品','写下一页航海记录','同一条船上的伙伴','驶向更开阔的水域']},
 {key:'portal',name:'无限展厅',family:'空间',layout:'architecture',bg:'#e9e6df',ink:'#494e55',accent:'#aa8261',symbol:'⊓',title:'推开一扇门，<br>遇见一个新世界。',description:'有厚度的建筑门框连续展开，鼠标改变透视。作品、手账、人物各是一间房，章节边框延续建筑比例。',action:'错开空间门框',chapters:['推开第一扇门','进入作品展厅','走进创作档案室','在会客厅相遇','最后一扇门通向你']},
 {key:'helix',name:'螺旋档案',family:'雕塑',layout:'spine',bg:'#171627',ink:'#ede9f5',accent:'#c5a5e8',symbol:'⌇',title:'每次探索，<br>都让想法再长一圈。',description:'双螺旋带着发光节点缓慢旋转；贯穿页面的中轴把作品、手账、人物串成一段向上的创作序列。',action:'舒展螺旋序列',chapters:['一段创作的序列','每个节点都是作品','读取生长的记录','让不同的人彼此配对','继续向上延伸']},
 {key:'clock',name:'灵感发条',family:'雕塑',layout:'workshop',bg:'#e9e1d1',ink:'#4f493b',accent:'#9b7240',symbol:'⚙',title:'让一个念头，<br>带动另一个。',description:'咬合齿轮与黄铜转轴组成微型机械装置。作品是零件、手账是装配图、伙伴是共同驱动这台机器的人。',action:'切换发条速度',chapters:['上紧一点好奇','看看运转的作品','打开装配记录','一起推动齿轮的人','让创造持续运转']},
 {key:'fabric',name:'织梦地形',family:'光学',layout:'textile',bg:'#ede8f1',ink:'#56495f',accent:'#a17aaa',symbol:'≋',title:'把不同的想法，<br>织成同一个世界。',description:'有经纬细节的三维织物起伏，弧面延伸为模块间的接缝。作品是纹样，手账是织法，人物是交织的线。',action:'改变织物张力',chapters:['从一根线开始','织出不同的作品','看看纹样背后的织法','让不同的线相遇','继续织向新的可能']},
 {key:'monolith',name:'字形建筑',family:'叙事',layout:'brutal',bg:'#e7e9df',ink:'#171d22',accent:'#f4663e',symbol:'SKY',title:'大胆一点。<br>把想法立起来。',description:'挤出厚度的 SKY 巨字像建筑一样排布。大字号、硬边分栏和横向编号延续到作品、档案与人物模块。',action:'拆开字形建筑',chapters:['把好奇立起来','作品就是我们的表达','拆开看它如何发生','把名字写得大一些','下一件事由你开始']},
 {key:'constellation',name:'星图漫游',family:'叙事',layout:'atlas',bg:'#111b32',ink:'#e3e8f2',accent:'#e4cc8c',symbol:'✧',title:'散落的好奇，<br>终会连成星图。',description:'三维星点与细线构成漂浮星图，滚动时重新排列。作品、记录、伙伴成为旅途的坐标，终点连回出发点。',action:'重排星图坐标',chapters:['找到自己的第一颗星','标记作品的坐标','留下探索的航迹','与同一片星空下的人相遇','下一段旅程从这里出发']}
];
